### ISSUE TITLE
UCM for Behringer UMC204HD broken

### ISSUE THREAD

**Issue by gregory112** [alsa-project/alsa-ucm-conf#177]
This is related: [https://github.com/alsa-project/alsa-ucm-conf/pull/128](https://github.com/alsa-project/alsa-ucm-conf/pull/128).
I came from this issue I filed in Pipewire: [https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2471](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2471).

So previously a while back, Behringer UMC204HD was detected as a single stereo input channel. This sound card has two inputs. However, just recently, the channel was separated into two mono channels, which was perfect. However, with the most recent update (I don't know if it's pipewire, pipewire-alsa, alsa-card-profiles, or alsa-ucm), it reverted back into the stereo single input (left/right) mode. What can I do to bring back the previous correct settings (apart from the bugs I filed in Pipewire)? I did not modify any ALSA UCM files.

Previously, a while back: it is detected as UMC204HD 192k (stereo input).
Then: UMC204HD 192k Line 1 (mono) and UMC204HD 192k Line 2 (mono) (this is how it's supposed to be, I think it's from the pull request above).
Now: Back to UMC204HD 192k (stereo input).

Might also be helpful but I am using pipewire. This is the output of `alsaucm listcards`:
```
ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) variable '${var:DirectCardName}' is not defined in this context!
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -22
ALSA lib parser.c:2957:(uc_mgr_scan_master_configs) Unable to open '-hw:2': Invalid argument
alsaucm: error failed to get card list: Invalid argument
```

There is an error for hw:2, which I assume is the Behringer. Here is the result of `alsaucm -chw:2 dump text`.
```
ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) variable '${var:DirectCardName}' is not defined in this context!
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -22
alsaucm: error failed to open sound card hw:2: Invalid argument
```

**Comment by gregory112** [comment]
I tested using the newest ALSA UCM from master branch and everything went back to normal. I guess the issue is fixed in this commit 2cc5a68e9798bc3226e2349fad5d3faa886368c1

**Comment by maru-sama** [comment]
Hello,

I seem to have the same issue but in my case using the master branch does not solve the issue. While it fixed the error mentioned above I now get no mixer for this device and init fails. I am running libasound version 1.2.7 and ucm HEAD from git.

The error I get is the following..
```
un 24 14:55:49 arthur kernel: usb 1-4: clock source 41 is not valid, cannot use
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Failed to find a working mixer device (_ucm000D.default:U192k).
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Failed to find a working mixer device (_ucm000D.default:U192k).
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Failed to find a working mixer device (_ucm000D.default:U192k).
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Failed to find a working mixer device (_ucm000D.default:U192k).
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur wireplumber[2077]: Unable to load mixer: No such file or directory
Jun 24 14:55:49 arthur pipewire[2074]: ALSA lib pcm_direct.c:1332:(snd1_pcm_direct_initialize_slave) unable to install hw params
Jun 24 14:55:49 arthur pipewire[2074]: ALSA lib pcm_dshare.c:711:(snd_pcm_dshare_open) unable to initialize slave
Jun 24 14:55:49 arthur pipewire[2074]: spa.alsa: '_ucm000D.umc204hd_stereo_out:U192k,0,0,1': playback open failed: No such device or address
Jun 24 14:55:49 arthur pipewire[2074]: mod.adapter: 0x5621ac5a9b10: can't get format: No such device or address
Jun 24 14:55:49 arthur pipewire[2074]: mod.adapter: usage: node.name=<string>
Jun 24 14:55:49 arthur kernel: usb 1-4: clock source 41 is not valid, cannot use
Jun 24 14:55:49 arthur kernel: usb 1-4: clock source 41 is not valid, cannot use
```
amixer also does not show any mixer device

**Comment by maru-sama** [comment]
alsaucm dump text seems to show the mixer though...
```
Verb.HiFi {
	Comment Default
	Device.Line1 {
		Comment "Line A"
		Values {
			CaptureCTL "_ucm0001.hw:U192k"
			PlaybackCTL "_ucm0001.hw:U192k"
			PlaybackChannels 2
			PlaybackMixer "_ucm0001.default:U192k"
			PlaybackMixerElem "Line A"
			PlaybackPCM "_ucm0001.umc204hd_stereo_out:U192k,0,0,1"
			PlaybackPriority 200
		}
	}
	Device.Line2 {
		Comment "Line B"
		Values {
			CaptureCTL "_ucm0001.hw:U192k"
			PlaybackCTL "_ucm0001.hw:U192k"
			PlaybackChannels 2
			PlaybackMixer "_ucm0001.default:U192k"
			PlaybackMixerElem "Line B"
			PlaybackPCM "_ucm0001.umc204hd_stereo_out:U192k,0,2,3"
			PlaybackPriority 100
		}
	}
	Device.Mic1 {
		Comment "Input 1"
		Values {
			CaptureCTL "_ucm0001.hw:U192k"
			CaptureChannels 1
			CaptureMixer "_ucm0001.default:U192k"
			CaptureMixerElem "Input 1"
			CapturePCM "_ucm0001.umc204hd_mono_in:U192k,0,0"
			CapturePriority 200
			PlaybackCTL "_ucm0001.hw:U192k"
		}
	}
	Device.Mic2 {
		Comment "Input 2"
		Values {
			CaptureCTL "_ucm0001.hw:U192k"
			CaptureChannels 1
			CaptureMixer "_ucm0001.default:U192k"
			CaptureMixerElem "Input 2"
			CapturePCM "_ucm0001.umc204hd_mono_in:U192k,0,1"
			CapturePriority 100
			PlaybackCTL "_ucm0001.hw:U192k"
		}
	}
}
Verb.Direct {
	Comment "Direct UMC204HD 192k"
	Device.Direct {
		Comment "Direct UMC204HD 192k"
		Values {
			CaptureCTL "_ucm0001.hw:U192k"
			CaptureChannels 2
			CapturePCM "_ucm0001.hw:U192k"
			CapturePriority 1000
			PlaybackCTL "_ucm0001.hw:U192k"
			PlaybackChannels 4
			PlaybackPCM "_ucm0001.hw:U192k"
			PlaybackPriority 1000
		}
	}
}
```

**Comment by maru-sama** [comment]
Here is the output, hope it helps.
[out.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8979035/out.txt)
t

**Comment by maru-sama** [comment]
please note this is with the ucm2 profile enabled

**Comment by maru-sama** [comment]
Please note I use pipewire and wireplumber in my setup here.

**Comment by maru-sama** [comment]
Ok, I think I found something...

When opening without ucm2
```
newfstatat(AT_FDCWD, "/usr/share/alsa/alsa.conf", {st_mode=S_IFREG|0644, st_size=10117, ...}, 0) = 0
openat(AT_FDCWD, "/dev/snd/controlC1", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffed9ee1550) = 0
close(3)                                = 0
```
In this case controlC1 gets opened..

with ucm
```
enat(AT_FDCWD, "/var/lib/alsa/card1.conf.d/ctl-remap.conf", O_RDONLY) = 13
newfstatat(13, "", {st_mode=S_IFREG|0644, st_size=894, ...}, AT_EMPTY_PATH) = 0
read(13, "ctl.default {\n\t@args.0 CARD\n\t@ar"..., 4096) = 894                                     
read(13, "", 4096)                      = 0
close(13)                               = 0
openat(AT_FDCWD, "/dev/snd/controlC2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/aloadC2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/snd/controlC3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/aloadC3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
In this case controlC1 is not even tried it is starting from C2 which obviously does not exist.

**Comment by perexg** [comment]
Could you show the full strace ?

**Comment by maru-sama** [comment]
Hi,
Attached you will find a working strace without UCM and a broken strace with UCM
[broken.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8980244/broken.txt)
[working.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8980245/working.txt)

**Comment by maru-sama** [comment]
Ok, I guess that's not the issue, there is something else happening in the UCM case.

**Comment by perexg** [comment]
```
openat(AT_FDCWD, "/dev/snd/controlC1", O_RDWR|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_PVERSION, 0x7ffdc51caa8c) = 0
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK|O_LARGEFILE) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_LIST, 0x7ffdc51cae90) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_LIST, 0x7ffdc51cae90) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51cab50) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ee0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51cab50) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ee0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51cab50) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ed0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ee0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51cab50) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ed0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ee0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51cab50) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_READ, 0x7ffdc51c9ee0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffdc51ca970) = -1 ENOENT (No such file or directory)
```

This is the issue. Could you attach the `/var/lib/alsa/card1.conf.d/ctl-remap.conf` file ?

**Comment by maru-sama** [comment]
Here the ctl_remap file that's generated for the device
[ctl-remap.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8980297/ctl-remap.conf.txt)

**Comment by perexg** [comment]
It seems that the driver offers different control names:

- "PCM Playback Volume" instead "UMC204HD 192k Output Playback Volume"
- "PCM Playback Switch" instead "UMC204HD 192k Output Playback Switch"

Could you change those names in configuration (`UMC204HD-HiFi.conf` file) if things will work?

**Comment by maru-sama** [comment]
I am not finding this in the conf file, could you explain this in more detail?

**Comment by maru-sama** [comment]
Ok, I made the change to the file and the ctl file now looks like this....
[ctl-remap.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8980439/ctl-remap.conf.txt)

but I still get the same error

**Comment by maru-sama** [comment]
I do not understand this...
amixer -D hw:U192k controls shows 
```
numid=7,iface=CARD,name='Internal Validity'
numid=3,iface=MIXER,name='PCM Playback Switch'
numid=4,iface=MIXER,name='PCM Playback Switch',index=1
numid=5,iface=MIXER,name='PCM Playback Volume'
numid=6,iface=MIXER,name='PCM Playback Volume',index=1
numid=8,iface=MIXER,name='Mic Capture Switch'
numid=9,iface=MIXER,name='Mic Capture Switch',index=1
numid=10,iface=MIXER,name='Mic Capture Volume'
numid=11,iface=MIXER,name='Mic Capture Volume',index=1
numid=2,iface=PCM,name='Capture Channel Map'
numid=1,iface=PCM,name='Playback Channel Map'
```

So yes "PCM Playback" is correct, but for whatever reason this still does not work

**Comment by maru-sama** [comment]
Ok,

I made it work by switching around the SRC and DST in the file. I can now select between the outputs and inputs. Please see the attached file as an example. Why do I need to switch this around though?
[ctl-remap.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8981768/ctl-remap.conf.txt)

**Comment by perexg** [comment]
Oops, it's my fault. I switched the argument use in common/ctl/remap.conf macro. Thank you for tests. Could you retest with the current master tree (above two commits) ?

**Comment by maru-sama** [comment]
Hello,

I tested it with this and it works better. alsamixer now no longer fails, BUT I have a different issue now. When I initially connect the device I see the following errors...
```
un 25 09:28:11 arthur pipewire[4627]: ALSA lib pcm_direct.c:1332:(snd1_pcm_direct_initialize_slave) unable to install hw params
Jun 25 09:28:11 arthur pipewire[4627]: ALSA lib pcm_dshare.c:711:(snd_pcm_dshare_open) unable to initialize slave
Jun 25 09:28:11 arthur kernel: usb 1-4: clock source 41 is not valid, cannot use
Jun 25 09:28:11 arthur pipewire[4627]: spa.alsa: '_ucm0008.umc204hd_stereo_out:U192k,0,2,3': playback open failed: No such device or address
Jun 25 09:28:11 arthur pipewire[4627]: mod.adapter: 0x55a690762300: can't get format: No such device or address
Jun 25 09:28:11 arthur pipewire[4627]: mod.adapter: usage: node.name=<string>
Jun 25 09:28:11 arthur kernel: usb 1-4: clock source 41 is not valid, cannot use
Jun 25 09:28:11 arthur pipewire[4627]: ALSA lib pcm_direct.c:1332:(snd1_pcm_direct_initialize_slave) unable to install hw params
Jun 25 09:28:11 arthur pipewire[4627]: ALSA lib pcm_dshare.c:711:(snd_pcm_dshare_open) unable to initialize slave
Jun 25 09:28:11 arthur pipewire[4627]: spa.alsa: '_ucm0009.umc204hd_stereo_out:U192k,0,0,1': playback open failed: No such device or address
Jun 25 09:28:11 arthur pipewire[4627]: mod.adapter: 0x55a690762300: can't get format: No such device or address
Jun 25 09:28:11 arthur pipewire[4627]: mod.adapter: usage: node.name=<string>
...
```
As a result I am not seeing the outputs. If I then change the profile of the card in pavucontrol to "off" and back to "default" the outputs and inputs appear. Could this be a race during init?

**Comment by gregory112** [comment]
I haven't got to test it with my own UMC204HD but I did a while back at times see 41 clock source is not valid error, which seems to be a USB issue, as the device is not recognized as audio device. I did some unplug and plugging though (or replacing the USB cable) and it went away. I will see after this if I see those errors with these new commits.

**Comment by maru-sama** [comment]
@gregory112 That's a different issue and is driver related, the clock source error is just a warning, but there have been fixes released yesterday for some other issues. 
Out of curiosity with the device attached is your computer able to suspend? In my case the device prohibits my notebook from going to standby and I have to unplug it before closing the lid.

**Comment by perexg** [comment]
The hw_params issue seems that the driver does not allow to set the requested parameters by the dshare alsa-lib plugin. Could you get some debug logs from pipewire to check which params cannot be installed ?

**Comment by maru-sama** [comment]
I am not seeing this issue, the problem apparently seems that pipewire is trying to open the device but then fails for some reason...

```
[I][00897.994096] spa.alsa     | [      alsa-pcm.c:  514 spa_alsa_open()] 0x562f18dca058: ALSA device open '_ucm0003.umc204hd_stereo_out:U192k,0,2,3' playback
ALSA lib pcm_direct.c:1332:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dshare.c:711:(snd_pcm_dshare_open) unable to initialize slave
[E][00897.995988] spa.alsa     | [      alsa-pcm.c:  516 spa_alsa_open()] '_ucm0003.umc204hd_stereo_out:U192k,0,2,3': playback open failed: No such device or address
[W][00897.996026] mod.adapter  | [       adapter.c:  219 find_format()] 0x562f18dca070: can't get format: No such device or address
[E][00897.996051] mod.adapter  | [module-adapter.c:  283 create_object()] usage: node.name=<string> 
[D][00897.996071] default      | [       private.h:  367 pw_core_resource_errorv()] resource 0x562f18b64460: id:9 seq:265 res:-22 (Invalid argument) msg:"usage: node.name=<string> "
[T][00897.996097] mod.protocol-native | [module-protocol-:  504 on_server_need_flush()] need flush
```

**Comment by gregory112** [comment]
@maru-sama Yes, just like you, I cannot suspend my laptop if the sound card is still connected.

**Comment by gregory112** [comment]
@maru-sama I actually did see your issue for a while, in which plugging the interface result in output being not detected, which I thought was related with the clock errors. I thought it was related to the USB connection, as I don't really see this issue anymore. I did actually change my USB cable, and try to just plug and unplug the interface. I really haven't seen this issue for a while, plugging the interface directly I can use it immediately without having to change profiles.

I haven't updated my UCM to the latest commits created by this issue though, did this issue happen after the latest commit, or happen even before?

**Comment by maru-sama** [comment]
@gregory112 I just got my device this friday so I never tried with an older version. That said my firmware is more recent than yours so I am also facing other issues. My main pet peeve is that I cannot turn the device OFF and with my setup (cabling) and the notebook not sleeping with it connected I have to find an alternative for now. 
To work around the UCM configuration not working every time I now changed the configuration in pipewire and do all the configuration there. But in the end I would also like go get UCM working.

**Comment by gregory112** [comment]
Any way to look for the current version of the firmware that I am using? I haven't used this for a long time actually, few months only, so I cannot say that this one is particularly new or old.

I wonder what "No such device" error mean. I also see it often in pipewire.
`spa.alsa: umc204hd_mono_in:U192k,0,0: snd_pcm_drop No such device`.

**Comment by maru-sama** [comment]
Yep correct, I was about the reply that as well. I have a new version of the firmware which requires some usb quirks for proper playback but the sleeping issue is there as well. Your firmware should not have any issues with playback cutting out. 
@perexg I did a short test regarding the UCM issue yesterday. For testing purposes I added a timeout timeout during the initialization like other audio devices [do](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/sound/usb/quirks.c?h=v5.18.7#n1126). 
As a result: 
 * alsa correctly applied the UCM, 
 * I saw no error messages in the logs from pipewire, 
 * BUT pavucontrol did not allow me to select any profile for the card

I will test this some more this evening, but could this really be a timing/interaction issue?

**Comment by gregory112** [comment]
You are using the 1.35 then? The patch for that has not been merged to upstream it seems, it is tracked in this issue, no? [https://bugzilla.kernel.org/show_bug.cgi?id=215934](https://bugzilla.kernel.org/show_bug.cgi?id=215934).

**Comment by maru-sama** [comment]
Correct, I applied it myself for my current kernel.

**Comment by perexg** [comment]
I cannot judge anything without logs. Maybe `spa-acp-tool -vvv -c 0 list-profilles` may print something. Replace zero number with your alsa card number (aplay -l).

**Comment by gregory112** [comment]
@maru-sama The patches there did not help you then? Do you have any issues with the 204 in Windows?

**Comment by maru-sama** [comment]
The quirks For the Poppinga worked fine. The Others For the click source did Not.

**Comment by gregory112** [comment]
As this seems to be driver/firmware issue should we close this issue then?

**Comment by maru-sama** [comment]
From my Site yes since the Last commits fixes the ucm Case.

**Comment by dyskette** [comment]
@perexg Hi. Is it possible the fix could be included in Fedora? The latest release 1.2.7.1 has the UMC204HD broken.

**Comment by gregory112** [comment]
@perexg You submitted two fixes, the direct card name and the mixer, and the direct card name one I think affects multiple soundcards. This might justify creating release 1.2.7.2?
